### ISSUE TITLE
More providers?? :-)

### ISSUE THREAD

**Issue by serramat** [VeNoMouS/Sick-Beard#19] opened 2018-03-28 18:07 UTC
Hi, I recently switched from junalmeida's repository to yours!!! ;-)

In the other repo I opened an issue where I asked if it was possible to add more providers (https://github.com/junalmeida/Sick-Beard/issues/309).

What do you think about this idea? I thought for example to RARBG (API link here: https://torrentapi.org/apidocs_v2.txt), 1337x, Extratorrent..

**Comment by VeNoMouS** [comment] 2018-03-28 20:07
aren't those trackers... not providers? either way sure I can look into it, i have one major thing to do with torrentday first before i can get to this, so maybe after this long weekend ... towards the end of next week?

**Comment by serramat** [comment] 2018-03-28 20:47
Of course!! No problem! ;-)

If you want I can send to you some code in Java and/or JavaScript for RARBG written by me if it can help you..

**Comment by VeNoMouS** [comment] 2018-04-09 06:43
@serramat well 0f742a47161bd82cdfd2a5e506bef45599e6a314 adds in rarbg for starters ...

**Comment by serramat** [comment] 2018-04-09 06:53
Awesome! Thanks! 👍 

You're the best! 🥇

**Comment by VeNoMouS** [comment] 2018-04-09 07:00
1337x is alot harder, as there is no direct download or magnet info on that search page.. you have to go inside each item returned by the search result page to get any download information....

as it stands, that isn't feasible for how sickbeard works... yes... we could scrape the living hell out of the website getting each download url when we search, but.. it comes back to WHY?!

**Comment by serramat** [comment] 2018-04-09 07:14
ooooh.. it's true! :-( I forgotten that!
No problem! ;-) For me eztv, torrentz and rarbg are the best..

**Comment by VeNoMouS** [comment] 2018-04-10 01:04
Cool cool, let me know of any other issues or addons you want.

**Comment by VeNoMouS** [comment] 2018-04-10 01:15
@serramat fixed a small bug when I was double checking my work before i fully closed this,

The bug is around the _doSearch() returning a list of dictionaries rather than a list of tuples,  It would break if you were backlog searching... this is due to the generic provider wrapper, ultimately I think I will move to dicts over tuples... but I will need to change every provider to return the correct list payload and also the generic doSearch function.

Anyway you will see a pending update on your end.. that's what the fix is for.

**Comment by serramat** [comment] 2018-04-10 06:24
I don't have the possibility to test it right now! :-( As soon as possible I'll feedback you..

Anyway..thank you for your work, I appreciate that!

**Comment by serramat** [comment] 2018-04-11 13:41
I've found these errors in my logs.. :-(

> 2018-04-11 13:45:41 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'nioevwut9a', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders'}, returned status code is 429
2018-04-11 09:45:42 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'uzob3vh716', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders'}, returned status code is 429
2018-04-11 05:45:44 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'uzob3vh716', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders'}, returned status code is 429
2018-04-11 01:45:42 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'uzob3vh716', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders'}, returned status code is 429

**Comment by VeNoMouS** [comment] 2018-04-12 02:29
Hrrm I'll look into that for you.

**Comment by serramat** [comment] 2018-04-12 06:47
Maybe I've found the problem..in the logs pasted above, I saw that the token isn't updated..
For example: the token 'uzob3vh716' is used in two research (2018-04-11 01:45:42 and 2018-04-11 05:45:44) but every token automatically expire in 15 minutes (I readed this in the guide: https://torrentapi.org/apidocs_v2.txt).

Is it possible is that the caused of 429 error code?

**Comment by VeNoMouS** [comment] 2018-04-12 09:28
@serramat i'll rewrite all the token code so its cleaner..  and yea, if the token is always the same most likely the cause, i'll do it tonight or tomorrow so expect an update with the next ~24hrs

**Comment by VeNoMouS** [comment] 2018-04-13 03:35
ok @serramat looked into this, tokens are always the same.... a that 429 error is actually a http status not the api json reply error, status code 429 is basicly saying stop spamming me, i've added on another second to the get requests to the server incase its that. lets see if you see get more of them i can always read the `Retry-After` that comes back in a 429... but hopefully the 429 is generated off the lack of long enough sleep time between requests.

**Comment by VeNoMouS** [comment] 2018-04-13 05:01
I've added in debug logging for status code 429 and outputing the Retry-After header so we can debug it a bit better if it occurs to you again.

**Comment by serramat** [comment] 2018-04-13 06:28
Thanks!
I've found 3 problems.. sorry.. :-(

1. 
> 2018-04-13 06:55:34 SEARCHQUEUE-MANUAL-SEARCH :: Error while searching Rarbg, skipping: RarbgProvider instance has no attribute '_validToken'

2. 
> 2018-04-13 11:51:22 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'fhld7vj2ki', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders'}, returned error code #4 / Invalid token. Use get_token for a new one!

3. I tried to search "silicon valley s05e02" but it respond with no result. But if I invoke the api from browser it respond to me with 5 torrents (https://torrentapi.org/pubapi_v2.php?mode=search&search_string=silicon%20valley%20S05E02&limit=100&format=json_extended&sort=seeders&token=fhld7vj2ki&category=1;18;41&app_id=myappid):

> {"torrent_results":[{"title":"Silicon.Valley.S05E02.Reorientation.1080p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv]","category":"TV HD Episodes","download":"magnet:?xt=urn:btih:acb9b9222e0b3f9a204208797dc9c60fdb9043c6&dn=Silicon.Valley.S05E02.Reorientation.1080p.AMZN.WEBRip.DDP5.1.x264-NTb%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce","seeders":435,"leechers":12,"size":1716720721,"pubdate":"2018-04-02 02:28:36 +0000","episode_info":{"imdb":"tt2575988","tvrage":"33759","tvdb":"277165","themoviedb":"60573","airdate":"2018-04-01","epnum":"2","seasonnum":"5","title":"Reorientation"},"ranked":1,"info_page":"https:\/\/torrentapi.org\/redirect_to_info.php?token=fhld7vj2ki&p=1_5_1_6_6_1_4__acb9b9222e"},{"title":"Silicon.Valley.S05E02.720p.WEB.H264-DEFLATE[rartv]","category":"TV HD Episodes","download":"magnet:?xt=urn:btih:dd74525469a4a4b22bec194d2100abf69de29b01&dn=Silicon.Valley.S05E02.720p.WEB.H264-DEFLATE%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce","seeders":342,"leechers":15,"size":605116438,"pubdate":"2018-04-02 02:22:47 +0000","episode_info":{"imdb":"tt2575988","tvrage":"33759","tvdb":"277165","themoviedb":"60573","airdate":"2018-04-01","epnum":"2","seasonnum":"5","title":"Reorientation"},"ranked":1,"info_page":"https:\/\/torrentapi.org\/redirect_to_info.php?token=fhld7vj2ki&p=1_5_1_6_6_1_1__dd74525469"},{"title":"Silicon.Valley.S05E02.WEB.H264-DEFLATE[rartv]","category":"TV Episodes","download":"magnet:?xt=urn:btih:cdaf730039377b7c8152af842aad0dedda05e749&dn=Silicon.Valley.S05E02.WEB.H264-DEFLATE%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce","seeders":195,"leechers":11,"size":157837981,"pubdate":"2018-04-02 02:22:08 +0000","episode_info":{"imdb":"tt2575988","tvrage":"33759","tvdb":"277165","themoviedb":"60573","airdate":"2018-04-01","epnum":"2","seasonnum":"5","title":"Reorientation"},"ranked":1,"info_page":"https:\/\/torrentapi.org\/redirect_to_info.php?token=fhld7vj2ki&p=1_5_1_6_6_1_0__cdaf730039"},{"title":"Silicon.Valley.S05E02.Reorientation.720p.AMZN.WEBRip.DDP5.1.x264-NTb[rartv]","category":"TV HD Episodes","download":"magnet:?xt=urn:btih:f50426648d1ec84d46fe0576e512a59f13da8648&dn=Silicon.Valley.S05E02.Reorientation.720p.AMZN.WEBRip.DDP5.1.x264-NTb%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce","seeders":103,"leechers":3,"size":617879001,"pubdate":"2018-04-02 02:27:22 +0000","episode_info":{"imdb":"tt2575988","tvrage":"33759","tvdb":"277165","themoviedb":"60573","airdate":"2018-04-01","epnum":"2","seasonnum":"5","title":"Reorientation"},"ranked":1,"info_page":"https:\/\/torrentapi.org\/redirect_to_info.php?token=fhld7vj2ki&p=1_5_1_6_6_1_3__f50426648d"},{"title":"Silicon.Valley.S05E02.1080p.WEB.H264-DEFLATE[rartv]","category":"TV HD Episodes","download":"magnet:?xt=urn:btih:5fe8660847e7d2fa18f9e9312567678159a8d50b&dn=Silicon.Valley.S05E02.1080p.WEB.H264-DEFLATE%5Brartv%5D&tr=http%3A%2F%2Ftracker.trackerfix.com%3A80%2Fannounce&tr=udp%3A%2F%2F9.rarbg.me%3A2710&tr=udp%3A%2F%2F9.rarbg.to%3A2710&tr=udp%3A%2F%2Fopen.demonii.com%3A1337%2Fannounce","seeders":79,"leechers":3,"size":1683750444,"pubdate":"2018-04-02 02:42:57 +0000","episode_info":{"imdb":"tt2575988","tvrage":"33759","tvdb":"277165","themoviedb":"60573","airdate":"2018-04-01","epnum":"2","seasonnum":"5","title":"Reorientation"},"ranked":1,"info_page":"https:\/\/torrentapi.org\/redirect_to_info.php?token=fhld7vj2ki&p=1_5_1_6_6_2_0__5fe8660847"}]}

**Comment by VeNoMouS** [comment] 2018-04-14 01:06
ah sorry , i'll clean that up, tbh i didn't test it that much as i was at work.

**Comment by VeNoMouS** [comment] 2018-04-14 01:08
re searching, have  you got it marked as HD or SD? because i only see 720/1080p results there.. you can look at your debug logs to see how it filter matched.

also 3) would be broken because of 1)

**Comment by VeNoMouS** [comment] 2018-04-14 01:22
re issue 2) I found this from the rarbg owner , https://github.com/pymedusa/Medusa/issues/442

So what i've done is bump the token session expiry to 10 minutes, lets see if that helps.

**Comment by serramat** [comment] 2018-04-14 07:20
Thanks for the first point.

Before found the second and the last points I've correct the validToken in isValidToken.
Maybe the error 3) is for the formatting pattern:

1. "silicon valley s05e02": 5 torrents
2. "silicon valley 5x02": no torrents 

> 2018-04-14 09:13:41 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: formatting pattern: %SN - %Sx%0E - %EN -> Silicon Valley - 5x02 - Reorientation
2018-04-14 09:13:41 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Unable to find a download for Silicon Valley - 5x02 - Reorientation

**Comment by VeNoMouS** [comment] 2018-04-14 08:11
@serramat yea i pushed an update for couple fixes earlier

**Comment by serramat** [comment] 2018-04-14 08:19
The error pasted above is after updated your code..
My last commit it's 2b1cf3f54a700337857e70402c2f5935bb2129fb

**Comment by VeNoMouS** [comment] 2018-04-14 08:29
which "error" you have a pattern match issue there ... you still havent told me if its HD or SD...

**Comment by VeNoMouS** [comment] 2018-04-14 08:31
All your results of the search there are HD that you have posted, if you have SD it wont format match.

**Comment by serramat** [comment] 2018-04-14 08:32
Sorry..you have right.. ;-) HD

**Comment by VeNoMouS** [comment] 2018-04-14 08:45
whats in your filtering log?

**Comment by VeNoMouS** [comment] 2018-04-14 08:46
it looks like this...

```
2018-04-14 17:14:16 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Checking if show Bosch S04E05 WEB H264-DEFLATE matches ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+)
2018-04-14 17:14:16 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Matched ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+) to Bosch S04E05 WEB H264-DEFLATE
2018-04-14 17:14:16 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Checking if show Bosch S04E05 720p WEB H264-DEFLATE matches ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+)
2018-04-14 17:14:16 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Matched ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+) to Bosch S04E05 720p WEB H264-DEFLATE
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Checking if show Bosch S04E05 720p WEB H264-DEFLATE matches ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+)
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Matched ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+) to Bosch S04E05 720p WEB H264-DEFLATE
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Checking if show Bosch S04E05 1080p WEB H264-DEFLATE matches ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+)
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Matched ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+) to Bosch S04E05 1080p WEB H264-DEFLATE
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Checking if show Bosch S04E05 WEB H264-DEFLATE matches ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+)
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Matched ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+) to Bosch S04E05 WEB H264-DEFLATE
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Checking if show Bosch S04E05 720p WEB H264-DEFLATE matches ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+)
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Matched ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+) to Bosch S04E05 720p WEB H264-DEFLATE
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Checking if show Bosch S04E05 1080p WEB H264-DEFLATE matches ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+)
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Matched ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+) to Bosch S04E05 1080p WEB H264-DEFLATE
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Checking if show Bosch S04E05 WEB H264-DEFLATE matches ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+)
2018-04-14 17:14:19 DEBUG    SEARCHQUEUE-BACKLOG-277928 :: Matched ^Bosch(?:\W+2015)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?:\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+) to Bosch S04E05 WEB H264-DEFLATE
```

**Comment by VeNoMouS** [comment] 2018-04-14 08:54
@serramat 720 or 1080?

**Comment by serramat** [comment] 2018-04-14 08:58
I found only these:
```
2018-04-14 09:13:41 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Checking if show Food.Paradise.S05E02.720p.HDTV.x264-NORiTE[rartv] matches ^Silicon\W+Valley(?:\W+2014)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?      :\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+)
2018-04-14 09:13:41 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Checking if show Food.Paradise.S05E02.720p.HDTV.x264-NORiTE[rartv] matches ^Silicon\W+Valley(?:\W+2014)?\W+(?:(?:S\d[\dE._ -])|(?:\d\d?x)|(?      :\d{4}\W\d\d\W\d\d)|(?:(?:part|pt)[\._ -]?(\d|[ivx]))|Season\W+\d+\W+|E\d+\W+)
2018-04-14 09:13:41 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Provider gave result Food.Paradise.S05E02.720p.HDTV.x264-NORiTE[rartv] but that doesn't seem like a valid result for Silicon Valley so I'm i      gnoring it
2018-04-14 09:13:41 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Picking the best result out of []
2018-04-14 09:13:41 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: No result picked.
2018-04-14 09:13:41 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2018-04-14 09:13:41 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Episode has no release group, replacing it with a generic one: %SN - %Sx%0E - %EN
2018-04-14 09:13:41 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: formatting pattern: %SN - %Sx%0E - %EN -> Silicon Valley - 5x02 - Reorientation
2018-04-14 09:13:41 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2018-04-14 09:13:41 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: Episode has no release group, replacing it with a generic one: %SN - %Sx%0E - %EN
2018-04-14 09:13:41 DEBUG    SEARCHQUEUE-MANUAL-SEARCH :: formatting pattern: %SN - %Sx%0E - %EN -> Silicon Valley - 5x02 - Reorientation
2018-04-14 09:13:41 INFO     SEARCHQUEUE-MANUAL-SEARCH :: Unable to find a download for Silicon Valley - 5x02 - Reorientation
```

720

**Comment by VeNoMouS** [comment] 2018-04-14 09:22
I'll check soon, playing pubg event atm .. :P

**Comment by VeNoMouS** [comment] 2018-04-14 10:24
Forgot search mode, in the payload :[

**Comment by serramat** [comment] 2018-04-14 10:48
oooooh yes!!! 👍 now it's worked!! :-)

**Closed as completed** 2018-04-14 12:32 UTC
Labels: enhancement, feature

**Comment by serramat** [comment] 2018-04-15 10:05
ooooooh noooo... :-( it's still bug here.. :-(

```
2018-04-15 08:47:21 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'hs0ge37qdm', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders', 'mode': 'list'}, returned error code #4 / Invalid token. Use get_token for a new one!
2018-04-15 08:47:21 SEARCHQUEUE-RSS-SEARCH :: Error while searching Rarbg, skipping: 'NoneType' object is not iterable
2018-04-15 08:47:11 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'hs0ge37qdm', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders', 'mode': 'list'}, returned error code #4 / Invalid token. Use get_token for a new one!
2018-04-14 20:47:20 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'6q4kgl1jxm', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders', 'mode': 'list'}, returned error code #4 / Invalid token. Use get_token for a new one!
2018-04-14 20:47:20 SEARCHQUEUE-RSS-SEARCH :: Error while searching Rarbg, skipping: 'NoneType' object is not iterable
2018-04-14 20:47:10 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'6q4kgl1jxm', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders', 'mode': 'list'}, returned error code #4 / Invalid token. Use get_token for a new one!
```

**Comment by VeNoMouS** [comment] 2018-04-15 11:07
Ok i'll look into it tomorrow for you

**Comment by VeNoMouS** [comment] 2018-04-15 11:21
@serramat threw in a hotfix.. give it a test out for me would you.

**Comment by VeNoMouS** [comment] 2018-04-15 21:56
@serramat any issues after that hotfix?

**Comment by serramat** [comment] 2018-04-16 04:06
Sometimes I've these errors in my logs
```
2018-04-16 01:32:54 SEARCHQUEUE-BACKLOG-277165 :: Error while searching Rarbg, skipping: 'NoneType' object is not iterable
2018-04-16 01:32:54 SEARCHQUEUE-BACKLOG-277165 :: No NZB/Torrent providers found or enabled in the sickbeard config. Please check your settings.
2018-04-15 21:27:26 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'bn4k3dp6wq', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders', 'mode': 'list'}, returned error code #4 / Invalid token. Use get_token for a new one!
2018-04-15 21:27:01 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'bn4k3dp6wq', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders', 'mode': 'list'}, returned error code #4 / Invalid token. Use get_token for a new one!
```
but tonight snatched a new episode of Silicon Valley..

**Comment by VeNoMouS** [comment] 2018-04-16 04:42
I need to look at 
```
2018-04-16 01:32:54 SEARCHQUEUE-BACKLOG-277165 :: Error while searching Rarbg, skipping: 'NoneType' object is not iterable
```

any maybe turn these into info rather than error..

```
2018-04-15 21:27:26 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'bn4k3dp6wq', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders', 'mode': 'list'}, returned error code #4 / Invalid token. Use get_token for a new one!
2018-04-15 21:27:01 SEARCHQUEUE-RSS-SEARCH :: [Rarbg] getURL() requested URL: https://torrentapi.org/pubapi_v2.php, with params: {'category': 'tv', 'search_string': '', 'min_leechers': 0, 'limit': 100, 'token': u'bn4k3dp6wq', 'min_seeders': 1, 'format': 'json_extended', 'app_id': 'sickbeard-torrentProviders', 'mode': 'list'}, returned error code #4 / Invalid token. Use get_token for a new one!```

**Comment by VeNoMouS** [comment] 2018-04-17 00:44
Pushed out a hotfix for you, try that.

**Comment by VeNoMouS** [comment] 2018-04-17 22:13
@serramat hows that hotfix goign for you?

**Comment by serramat** [comment] 2018-04-18 05:15
It's worked.
In my error logs I don't see none of previous errors.
